# Generated by Django 3.2.13 on 2022-06-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='status',
            name='like',
        ),
    ]
