# Generated by Django 3.2.13 on 2022-07-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_votetracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteTracker',
        ),
    ]
