# Generated by Django 3.2.13 on 2022-07-07 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0007_votetracker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoteTracker',
            new_name='StatusVoteTracker',
        ),
        migrations.AddField(
            model_name='status',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
