# Generated by Django 3.2.13 on 2022-07-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0008_auto_20220707_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='comment',
            new_name='comments',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.status')),
            ],
        ),
    ]
