# Generated by Django 3.2.13 on 2022-07-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_auto_20220707_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
