# Generated by Django 3.2.13 on 2022-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_auto_20220713_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='photo',
            new_name='status_photo',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image/'),
        ),
    ]
