# Generated by Django 3.2.13 on 2022-07-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0015_auto_20220713_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='base_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsfeed.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsfeed.status'),
        ),
    ]
