# Generated by Django 3.2.13 on 2022-07-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0016_auto_20220713_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
