# Generated by Django 3.2.13 on 2022-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0017_alter_status_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments_on_comment',
            field=models.IntegerField(default=0),
        ),
    ]
